language: generic
sudo: required
dist: trusty
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build
script:
- docker-compose run web typesafety --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: sq0ZxGtZn8rxBk5PihV0+KbDLpKsBlHzkSJiJjO3fCzKxv8+tP1j7d+i3KJmw+Pbur7y1Df9QRZbgOqNuL6XnksP3LlGoWJkteO5+Sed/kHW7opQOsCl5RvJHLTrfLjUdzfbgmhGhAPXsWeB9casvG72GGDl6dG1bQujLDcPv2fKc3xB3alvzVtqi14WAzVYN1IMf+pLEiy6iL5wkmZWf5vvv0kzkZYS8JAM8hGhA6KTwYh/16zJyJAMSWFjoTaZ1o/Pfl2X51pKZ1xee9CGy7rLhwMDtlnC9oJ9Xk0lccEJla8qSJZabU/9+u3mf+3y0gUKj3xFUk/JW5dVU8PluR8myaui+4pRZ6FAAh7S57Mf+6eFvswXmQeKoM7F5hCIY3EwchEnEU+tN3ps8LqvDPyNxBYvxsKJw4g9FRYiMDf+P4iY10yzsFjzX9Uu56Uk+9UNAWTKrX/xurbB/lMjf1tzc7An3meCGxoQqdCqDxQ+ZCkwlVzqIlcC9dgisTOFkm9cMI1wbpWIl+t3LuIEITOZCYpa3n1mfgdkUCPFTT2m+/yUJYu1zL6TSjA/LyRnVGcL82S1MXsDYZ+KZFfHlTbHFGfAZVPKRkhN3Zcw3YVEu+D1dW1TdR5P4I32I+LWJV4IX0UMTmJOMUmZu6jTCr7/cZl7GRwxrETk+2hl6uY=
  - secure: HRbKBTCmH0ZsWTyDbVSgeydRTCPJAsx3V9UzeN3ScUOylqumlhUpv5OuwcDL9ar8lHKl/Ty2DGh1xTzgvSowQsQaBS5FZh7zYOwFvx+2CV5x2H+bqKD95MrXl/VIRAtR6rpGe9HV2uGR6BcvM7hVgJq+3n1S5OAgeDpzwldsw9icpW0NYXZ1nnNOqlkxjDclnTmFrTVzk/e1Zo2XIsv7eKRkYr1YQttyVEMMAazngQr+R7I3Rm+u0XftNkhW6GtWvMJl2hIKwODOTBBWj7q3mHgArXbrZRH5Li0341kI8+1a25KOv6XUxw92uk30FvYcSfzSunXqo6NwmD5f3ON54EHKVUaosW19AmBGK/AvdO3UWqmI2O3zA5+OlWhreDUnTbgfnhOGAGsK7HCpbIyFT3gCj/OTTsC4Rkay7Ua/fy9bzIui191Fx5FrIeW9W6+n8L2VEX7AKpCgPtFIlXLM55LIC4psiqcDGo4ay3i6QzMCyRwP/8Uvky1ivz/8SWeHBSliHGhtWNLnv9Gl30BXRCWfoH7NKEYNKI7g/eqryQFUMBwa18oJUnJL7taxlf3GYing4kZzCKo/KIdfTURVIu5yKB1ry1xybKDlM1upPgT8Yn/kBd/uScmO3yCY/L9T2A8BY/H6D2KSGjLcjDsgWFgF0Htxr66fi2u37ZxDwDo=
